POST http://localhost:7071/userupdated
Content-Type: application/json

{
    "specversion" : "1.0",
    "type" : "user.updated",
    "source" : "ClientApp",
    "subject": null,
    "id" : "123456789",
    "time" : "2021-01-16T17:31:00Z",
    "datacontenttype" : "application/json",
    "data" : [
        {"id": "123", "givenName": "Paco", "familyName": "de la Cruz"},
        {"id": "234", "givenName": "Xavier", "familyName": "Aguirre"}
    ]
}

